[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
tip-router-operator-cli = { workspace = true }
solana-accounts-db = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }